### ISSUE TITLE
Generic JSONField for all db drivers

### ISSUE THREAD

**Issue by Zeliboba5** [Zeliboba5/tortoise-orm#18]
Currently there is only implementation for postgres using `jsonb`. It will be good thing to implement generic field that could be used for basic storing of JSON

**Comment by grigi** [comment]
I would love a feature emulation framework, where a JSONField by default would be emulated using a TextField, but if using PostgreSQL it can be "upgraded" to a faster more searchable variant?

We are already doing it for, e.g. date/time fields and SQLite. it is actually a varchar in the DB, and when you read you get a string, not a date/time object back.

**Comment by Zeliboba5** [comment]
I think it shouldn't be a problem to patch real field we are using in the `Tortoise.init()` - it should be just a matter of making few dicts with mapping of `ClientClass => Field` and storing this dicts inside the field itself. I think it will be quite extendable for future uses and may be even for custom fields.

I will look into it when will get to this issue

**Comment by grigi** [comment]
I have started porting this over, and the PG schema_generator injects the type difference.
That should get it "working", but not all the extra features, like partial searching.

In concert with this I'm planning to do more testing on the model fields themselves.

**Comment by grigi** [comment]
Close this please? Or give me permissions to close it?
