### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by Zeliboba5** [Zeliboba5/tortoise-orm#2]
Right now I don't have good idea on how to make test. 
I think I could make dummy backend for easy one query tests, and use sqlite for more complex ones, but still looking for better ideas

**Comment by grigi** [comment]
I have been considering this, and want to do a crack at it.

I plan to do in rough order of preference:
* [ ] Management infrastructure
* [ ] Tests for stateless code
* [ ] get it to work in tox locally
* [ ] set up travis (I'll probably need your assistance as the project owner)
* [ ] use your examples as reference to start on some tests that test stateful stuff (HARD)

**Comment by grigi** [comment]
Progress in #16
